export enum CANDIDATES {
  REGISTERED = "REGISTERED",
  EXISTING_PHONE = "EXISTING_PHONE",
}

export enum SESSIONS {
  CREATED = "CREATED",
}

export enum PAYMENTS {
  INITIALIZED = "INITIALIZED",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
  CARD_UPLOADED = "CARD_UPLOADED",
}
