export enum PAYMENT_STATUS {
  INITIALIZED = "INITIALIZED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum PROVIDER {
  OM = "OM",
  MOMO = "MOMO",
}

export enum INTOUCH_PROVIDER {
  // OM = "PAIEMENTMARCHANDOM",
  OM = "CM_PAIEMENTMARCHAND_OM_TP",
  MOMO = "PAIEMENTMARCHAND_MTN_CM",
}
